import { indieFlower } from "@/app/data/fonts"
import Link from "next/link"
import styles from "./layout.module.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}: { children: React.ReactNode}) {
  return (

    <html lang="en">
      <body className={`${indieFlower.className}`}>

        <header className={`${styles.header}`}>

          <Link className={`${styles.header_logo_link}`} href={"/"}>
            <img className={`${styles.header_logo}`} src="pageLogo.png" alt="Sweet Bliss Bakery Logo" />
          </Link>


          <nav className={`${styles.header_nav}`}
          >
            
            <ul className={`${styles.header_nav_menu}`} >

              <li className={`${styles.header_nav_menu_item}`}>
                <a href="">Popular</a>
              </li>

              <li className={`${styles.header_nav_menu_item}`} >
                <a href="">New</a>
              </li>

              <li className={`${styles.header_nav_menu_item}`} >
                <a href="">About Us</a>
              </li>

              <li className={`${styles.header_nav_menu_item}`} >
                <a href="">Types ▼</a>

                <ul className={`${styles.header_nav_menu_item_subMenu}`}>

                  <li>
                    <a href="">Cookies</a>
                  </li>

                  <li>
                    <a href="">Ice Creams</a>
                  </li>

                  <li>
                    <a href="">Fried</a>
                  </li>

                  <li>
                    <a href="">Fruits</a>
                  </li>

                </ul>

              </li>

            </ul>
            
          </nav>


        </header>

        {children}
      </body>
    </html>

  )
}
