import { indieFlower } from "@/app/data/fonts"
import { Header } from "./Components/header/header"
import { Footer } from "./Components/footer/footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}: { children: React.ReactNode}) {

  return (

    <html lang="en">
      <body className={`${indieFlower.className}`}>

        <Header/>

        {children}

        <Footer/>


      </body>
    </html>

  )
}
