import { indieFlower } from "@/app/data/fonts"
import Link from "next/link"
import styles from "./layout.module.css"
import { MenuSVG } from "./SVG/MenuSVG"
import Image from "next/image"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}: { children: React.ReactNode}) {

  return (

    <html lang="en">
      <body className={`${indieFlower.className}`}>

        <header className={`${styles.header}`}>

          <Link className={`${styles.header_logo_link}`} href={"/"}>
            <Image priority width={90} height={65} className={`${styles.header_logo}`} src="/pageLogo.png" alt="Sweet Bliss Bakery Logo"/>
          </Link>

          <MenuSVG className={`${styles.header_menuSVG}`}/>

          <nav className={`${styles.header_nav}`}>
            
            <ul className={`${styles.header_nav_menu}`} >

              <li className={`${styles.header_nav_menu_item}`}>
                <Link href="">Popular</Link>
              </li>

              <li className={`${styles.header_nav_menu_item}`} >
                <Link href="">New</Link>
              </li>

              <li className={`${styles.header_nav_menu_item}`} >
                <Link href="">About Us</Link>
              </li>

              <li className={`${styles.header_nav_menu_item}`} >
                <Link href="">Types ▼</Link>

                <ul className={`${styles.header_nav_menu_item_subMenu}`}>

                  <li>
                    <Link href="">Cookies</Link>
                  </li>

                  <li>
                    <Link href="">Ice Creams</Link>
                  </li>

                  <li>
                    <Link href="">Fried</Link>
                  </li>

                  <li>
                    <Link href="">Fruits</Link>
                  </li>

                </ul>

              </li>

            </ul>
            
          </nav>


        </header>

        {children}
      </body>
    </html>

  )
}
